export type Bird = {
  shortName: string;
  lvrpaName: string;
  ebirdName: string;
}
export const birds: Bird[] = [["G Goose", "Greylag Goose", "Greylag Goose"],
  ["C Goose", "Canada Goose", "Canada Goose"],
  ["E Goose", "Egyptian Goose", "Egyptian Goose"],
  ["Swan", "Mute Swan", "Mute Swan"],
  ["Shovlr", "Shoveler", "Northern Shoveler"],
  ["Gadwall", "Gadwall", "Gadwall"],
  ["Mallard", "Mallard", "Mallard"],
  ["Teal", "Teal", "Eurasian Teal"],
  ["Pochard", "Pochard", "Common Pochard"],
  ["Tuftie", "Tufted Duck", "Tufted Duck"],
  ["L Grebe", "Little Grebe", "Little Grebe"],
  ["F Pigeon", "Feral Pigeon", "Feral Pigeon"],
  ["S Dove", "Stock Dove", "Stock Dove"],
  ["W Pigeon", "Woodpigeon", "Common Woodpigeon"],
  ["C Dove", "Collared Dove", "Collared Dove"],
  ["W Rail", "Water Rail", "Water Rail"],
  ["Moorhen", "Moorhen", "Common Moorhen"],
  ["Coot", "Coot", "Eurasian Coot"],
  ["BH Gull", "Black-headed Gull", "Black-headed Gull"],
  ["C Gull", "Common Gull", "Common Gull"],
  ["H Gull", "Herring Gull", "European Herring Gull"],
  ["LBBG", "Lesser Black-Backed Gull", "Lesser Black-Backed Gull"],
  ["C'm'ant", "Cormorant", "Great Cormorant"],
  ["Heron", "Grey Heron", "Grey Heron"],
  ["Egret", "Little Egret", "Little Egret"],
  ["Sprawk", "Sparrowhawk", "Eurasian Sparrowhawk"],
  ["Kingfisher", "Kingfisher", "Common Kingfisher"],
  ["Gr Wood", "Green Woodpecker", "Eurasian Green Woodpecker"],
  ["GS Wood", "Great Spotted Woodpecker", "Great Spotted Woodpecker"],
  ["Peregrine", "Peregrine", "Peregrine Falcon"],
  ["Parakeet", "Ring-necked Parakeet", "Ring-necked Parakeet"],
  ["Jay", "Jay", "Eurasian Jay"],
  ["Magpie", "Magpie", "Common Magpie"],
  ["Crow", "Carrion Crow", "Carrion Crow"],
  ["Blue Tit", "Blue Tit", "Eurasian Blue Tit"],
  ["Great Tit", "Great Tit", "Great Tit"],
  ["Chiff", "Chiffchaff", "Common Chiffchaff"],
  ["Cetti", "Cetti's Warbler", "Cetti's Warbler"],
  ["Lottie", "Long-tailed Tit", "Long-tailed Tit"],
  ["Goldcrest", "Goldcrest", "Goldcrest"],
  ["Wren", "Wren", "Eurasian Wren"],
  ["S Thrush", "Song Thrush", "Song Thrush"],
  ["Redwing", "Redwing", "Redwing"],
  ["Blackbird", "Blackbird", "Eurasian Blackbird"],
  ["Robin", "Robin", "European Robin"],
  ["Dunnock", "Dunnock", "Dunnock"],
  ["Gr Wag", "Grey Wagtail", "Grey Wagtail"],
  ["Pie Wag", "Pied Wagtail", "Pied Wagtail"],
  ["Chaffinch", "Chaffinch", "Common Chaffinch"],
  ["Gr-finch", "Greenfinch", "European Greenfinch"],
  ["Goldfinch", "Goldfinch", "European Goldfinch"]].map(([shortName, lvrpaName, ebirdName]) => ({shortName, lvrpaName, ebirdName}));
